name: Deploy MiniStock

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar config.js dinamicamente
        run: |
          mkdir -p script
          echo "const CONFIG = { API_URL: '${{ secrets.API_URL }}' };" > script/config.js
          echo "✅ Arquivo config.js gerado com sucesso!"

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy para o Pages
        id: deployment
        uses: actions/deploy-pages@v4